export const REVIEW_SOURCES = {
  TRUST_PILOT: "trust_pilot",
} as const;

export const DEFAULT_REVIEWS = [
  {
    id: "6901e54157f842e3d010f851",
    filtered: false,
    pending: false,
    text: "In-depth survey and personal service, would recommend.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-29T11:58:25.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "In-depth survey and personal service",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-28T00:00:00.000Z",
      publishedDate: "2025-10-29T11:58:25.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "621bcf2ce4f1540013c35daa",
      displayName: "Pamela",
      imageUrl: "",
      numberOfReviews: 7,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Pamela, \n\nThank you for your review. \n\nI am pleased to read you were happy with the service and would recommend us. I will be sure to pass this on the surveyor! \n\nI am glad we were able to be of service to you. \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-29T12:16:20.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "6900ef57bc162f6f8bcc84e8",
    filtered: false,
    pending: false,
    text: "Very happy with the service. ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-28T18:29:11.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Very happy with the service.",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-17T00:00:00.000Z",
      publishedDate: "2025-10-28T18:29:11.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "6900ef57ec11db6328102bb6",
      displayName: "Ben Holland",
      imageUrl: "",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Ben,\n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-29T08:32:14.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "6900c33054490c3eb3308133",
    filtered: false,
    pending: false,
    text: "Very quick to book the survey and take the money. It's downhill from there. Allegedly the surveyor had a spell in hospital. It's a pity that the computer issues he had and was unable to rectify didn't happen while he was in the hospital. It would also help if houzecheck were able to speak to him. Then of course the new looking 20 year old kitchen, and the combi boiler with a hot water storage cylinder. Steer clear.",
    rating: 1,
    labels: {
      merged: null,
      verification: {
        isVerified: false,
        createdDateTime: "2025-10-28T15:20:48.000Z",
        reviewSourceName: "Organic",
        verificationSource: "invitation",
        verificationLevel: "not-verified",
        hasDachExclusion: false,
      },
    },
    title: "Very quick to book the survey and take…",
    likes: 0,
    source: "Organic",
    dates: {
      experiencedDate: "2025-07-07T00:00:00.000Z",
      publishedDate: "2025-10-28T15:20:48.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "6053823a56f07b0019e8071a",
      displayName: "Martin  Allum",
      imageUrl: "",
      numberOfReviews: 4,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Martin, \n\nThank you for your review. \n\nI am sorry to hear that you were disappointed. \n\nWe would be very happy to investigate any issues for you. We pride ourselves on offering a high level of service and so if you are not happy, please could you call us on 0203 936 9033 or email us on team@houzecheck.com so we can look into these issues for you. \n\nAll of our surveyors are fully qualified surveyors registered with the RICS (Royal Institution of Chartered Surveyors) and work to RICS' exacting standards. We would therefore be keen to investigate your concerns. \n\nKind regards, \n\nDan\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-28T17:04:25.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68ff415e533a83bfcb8dff2a",
    filtered: false,
    pending: false,
    text: "Very  professional and friendly service, was called after the survey was complete to explained and go through the report which was so helpful,  5* experience.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-27T11:54:38.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "5* service ",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-18T00:00:00.000Z",
      publishedDate: "2025-10-27T11:54:38.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "5cdaf6e794dddb5a1d8a1e33",
      displayName: "Sharon Carter",
      imageUrl: "",
      numberOfReviews: 6,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Sharon, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-27T12:12:41.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fea4d35f008f7fa31d7f33",
    filtered: false,
    pending: false,
    text: "The lady was very good she did more than we expected brilliant photos which showed us a few things we never spotted and we were able to tell solicitor what we wasn’t happy with . I would 100 per cent recommend your company ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-27T00:46:43.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Good check",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-19T00:00:00.000Z",
      publishedDate: "2025-10-27T00:46:43.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "608930a104832a001a8716ef",
      displayName: "Yvonne",
      imageUrl:
        "https://user-images.trustpilot.com/608930a104832a001a8716ef/73x73.png",
      numberOfReviews: 18,
      countryCode: "GB",
      hasImage: true,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Yvonne, \n\nThank you for your review. \n\nI am pleased to read you were happy with the service and would recommend us. I will be sure to pass this on the surveyor! \n\nI am glad we were able to be of service to you. \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-27T09:22:09.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fd02f34f1ce7226bf3b712",
    filtered: false,
    pending: false,
    text: "Extremely unprofessional the guy kept on cancelling 3 time also the customer service is really bad they stop responding as soon as yhe payment is done.",
    rating: 1,
    labels: {
      merged: null,
      verification: {
        isVerified: false,
        createdDateTime: "2025-10-25T19:03:47.000Z",
        reviewSourceName: "BasicLink",
        verificationSource: "invitation",
        verificationLevel: "invited",
        hasDachExclusion: false,
      },
    },
    title: "Extremely unprofessional the guy kept…",
    likes: 0,
    source: "BasicLink",
    dates: {
      experiencedDate: "2025-10-21T00:00:00.000Z",
      publishedDate: "2025-10-25T19:03:47.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "5bbbce5b4de5666d34abc963",
      displayName: "Mezba Uddin",
      imageUrl:
        "https://user-images.trustpilot.com/5bbbce5b4de5666d34abc963/73x73.png",
      numberOfReviews: 7,
      countryCode: "GB",
      hasImage: true,
      isVerified: true,
    },
    reply: {
      message:
        "Dear Mezba, \n\nThank you for your review. \n\nWe’re very sorry to hear about the difficulties you experienced when scheduling your survey.\n\nThe first appointment needed to be rescheduled as we were unable to reach the vendor to confirm access. On the second occasion, the survey did not appear in the surveyor’s diary due to the booking being made at short notice. We promptly rescheduled to the next available date, and the survey was completed a few days later.\n\nWe appreciate your patience and understanding, and we’ll continue to improve our scheduling process to help prevent this from happening again.\n\nKind regards,\n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-27T10:40:44.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fcd6b895b338a8afa11de6",
    filtered: false,
    pending: false,
    text: "I was really pleased with the level of service attained from the start to the end.  The team worked efficiently and kept me in the loop on progress at every stage.  Thank you for your co-operation.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-25T15:55:04.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Great setvice",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-09T00:00:00.000Z",
      publishedDate: "2025-10-25T15:55:04.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "68fcd6b7c5450bd3522e8738",
      displayName: "Kwabena Okyere",
      imageUrl: "",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Kwabena, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-27T09:17:20.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fc9a6a678cadacb9248016",
    filtered: false,
    pending: false,
    text: "This company is fantastic to deal with they are thorough and the follow up is great. ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-25T11:37:46.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "This company is fantastic to deal with…",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-24T00:00:00.000Z",
      publishedDate: "2025-10-25T11:37:46.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "5fa6c72f339802001ac39332",
      displayName: "Mr D Kittlety",
      imageUrl: "",
      numberOfReviews: 36,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Mr Kittlety,\n\nThank you for your review.\n\nWe are pleased to hear that you are happy with our services and that we met your expectations.\n\nAll the best!\n\nDalvin\nCustomer Services\n0203 936 9033",
      publishedDate: "2025-10-27T09:24:16.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fbd4f6c0413f691646d1df",
    filtered: false,
    pending: false,
    text: "My experience was very good. I was impressed by the fast service, the reasonable price, and the detailed report. I would use them again if I need to.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-24T21:35:18.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "My experience was very good!",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-17T00:00:00.000Z",
      publishedDate: "2025-10-24T21:35:18.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "5a2c123b0000ff000aeeb0fb",
      displayName: "Kristina Hani-Elaoud",
      imageUrl: "",
      numberOfReviews: 10,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Kristina, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-27T09:14:48.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fbb689a6890c2a16fb549c",
    filtered: false,
    pending: false,
    text: "Excellent service, quick & efficient. ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-24T19:25:29.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Excellent service",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-17T00:00:00.000Z",
      publishedDate: "2025-10-24T19:25:29.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "670d4f89dc697155d9651551",
      displayName: "Abigail Webster",
      imageUrl: "",
      numberOfReviews: 2,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Abigail, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-27T09:14:12.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68fa6818e4bf6fd7e6efff0c",
    filtered: false,
    pending: false,
    text: "We had an extremely prompt reply to our online form, they looked at the property within a week and sent through report within 24 hours.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: false,
        createdDateTime: "2025-10-23T19:38:32.000Z",
        reviewSourceName: "BasicLink",
        verificationSource: "invitation",
        verificationLevel: "invited",
        hasDachExclusion: false,
      },
    },
    title: "We had an extremely prompt reply to our…",
    likes: 0,
    source: "BasicLink",
    dates: {
      experiencedDate: "2025-10-21T00:00:00.000Z",
      publishedDate: "2025-10-23T19:38:32.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "685fa8f14e662db5a25326a7",
      displayName: "Jack rose",
      imageUrl: "",
      numberOfReviews: 2,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Jack, \n\nThank you for your review. \n\nI am pleased to read you were happy with the experience and would recommend us. We stride to be as efficient where possible so you are not waiting long when it comes to making an important decision.\n\nI am glad we were able to be of service to you and wish you the best for the future!\n\nKind regards, \n\nDan\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-24T10:07:55.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f9c31fb156da47f2a0d283",
    filtered: false,
    pending: false,
    text: "Anthony was amazing at guiding us through the process.  ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: false,
        createdDateTime: "2025-10-23T07:54:39.000Z",
        reviewSourceName: "BasicLink",
        verificationSource: "invitation",
        verificationLevel: "invited",
        hasDachExclusion: false,
      },
    },
    title: "Anthony was amazing at guiding us…",
    likes: 0,
    source: "BasicLink",
    dates: {
      experiencedDate: "2025-10-23T00:00:00.000Z",
      publishedDate: "2025-10-23T07:54:39.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "68f9c31a519d8fd87ae59ef9",
      displayName: "Jawaad MALIK",
      imageUrl:
        "https://user-images.trustpilot.com/68f9c31a519d8fd87ae59ef9/73x73.png",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: true,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Jawaad,\n\nThank you for your review.\n\nWe are pleased to hear that you are happy with the service Anthony provided you with and he was able to met your expectations.\n\nAll the best!\n\nDalvin\nCustomer Services\n0203 936 9033",
      publishedDate: "2025-10-23T08:22:33.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f8f4dbe0e94ab8a4c42e1b",
    filtered: false,
    pending: false,
    text: "Very though survey ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-22T17:14:35.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Very thorough survey",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-19T00:00:00.000Z",
      publishedDate: "2025-10-22T17:14:35.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "5da0c9054656ee53b8a48fca",
      displayName: "Mandy Kirk",
      imageUrl:
        "https://user-images.trustpilot.com/5da0c9054656ee53b8a48fca/73x73.png",
      numberOfReviews: 7,
      countryCode: "GB",
      hasImage: true,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Mandy,\n\nThank you for your review.\n\nWe are pleased to hear that you are happy with our services and that the report met your expectations.\n\nAll the best!\n\nDalvin\nCustomer Services\n0203 936 9033",
      publishedDate: "2025-10-23T08:15:53.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f84dbacfcf7faf7206e4d8",
    filtered: false,
    pending: false,
    text: "Customer service was excellent. They told me everything I needed to know and what would happen next. They explained about the different levels of valuations and  about the price. The date they have available. They was very professional over the phone. Simon the surveyor who came out was a lovely gentleman very professional respectful and smartly dressed. He explained what he was going to be doing and explained what happens next. They kept me updated on the process. It’s only took about 4 to 5 days to come through my email. I’ve never used houzecheck before I will definitely use again if needed. I will definitely be recommending houzecheck to family and friends highly recommend I have give 5*.  Because it is deserved 5*",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-22T05:21:30.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Fantastic customer service ",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-11T00:00:00.000Z",
      publishedDate: "2025-10-22T05:21:30.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "5e7378f4dffcf7237d8de08c",
      displayName: "Colette ",
      imageUrl: "",
      numberOfReviews: 27,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Colette, \n\nThank you for your review. \n\nWe really appreciate your feedback and are very pleased we were able to assist you. I will pass this on to the surveyor, Simon, as I am sure they will also be delighted. \n\nBest of luck with the purchase! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-22T08:00:56.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f7c6358fc9365d3d14ebfa",
    filtered: false,
    pending: false,
    text: "Amazing service, report came back after 4 days and very detailed.",
    rating: 4,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-21T19:43:17.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Swift",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-12T00:00:00.000Z",
      publishedDate: "2025-10-21T19:43:17.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "68f7c634abede227c7da8f9c",
      displayName: "Pat Fakua",
      imageUrl: "",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Pat, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-22T07:57:16.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f7aec210c96c2e26723ce1",
    filtered: false,
    pending: false,
    text: "Efficiency in carrying out the survey, good communication and I was kept informed of the process throughout.\nI got a very detailed survey report within 2 days and I was also given advise on what actions to take on matters that needs attention. I can definitely recommend this company.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-21T18:03:14.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Efficiency in carrying out the survey",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-10T00:00:00.000Z",
      publishedDate: "2025-10-21T18:03:14.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "57fa6f260000ff000a4bdf2a",
      displayName: "Theresa",
      imageUrl: "",
      numberOfReviews: 18,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Theresa, \n\nThank you for your review. \n\nI am pleased to read you were happy with the service and would recommend us. I will be sure to pass this on the surveyor! \n\nI am glad we were able to be of service to you. \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-22T07:56:28.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f797c8f5ab86ff9012f9d8",
    filtered: false,
    pending: false,
    text: "Easy to contact.Prompt response to request.Clear advice given on the type of survey required.\nSurvey completed and report completed within a couple of days.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-21T16:25:12.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Easy to contact.Prompt responHouse surveyse to…",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-07T00:00:00.000Z",
      publishedDate: "2025-10-21T16:25:12.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "68f797c8a9dcb0de2bfe8cea",
      displayName: "customer",
      imageUrl: "",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Customer, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-22T07:49:00.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f661fccbe2e1d36908a6ca",
    filtered: false,
    pending: false,
    text: "Very efficient arrangement from quotation to conduction of survey and surprisingly report received the next day. Finding and professional advice is detailed in report. Very nice survey and valuable information conveyed. Generic pictures showing the parts of property (e.g. garden, garage, interior, view from side or rear, etc. ) inspected can be included in the report. Professional survey and Recommended.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: false,
        createdDateTime: "2025-10-20T18:23:24.000Z",
        reviewSourceName: "BasicLink",
        verificationSource: "invitation",
        verificationLevel: "invited",
        hasDachExclusion: false,
      },
    },
    title: "Very efficient survey arrangement",
    likes: 0,
    source: "BasicLink",
    dates: {
      experiencedDate: "2025-10-15T00:00:00.000Z",
      publishedDate: "2025-10-20T18:23:24.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "64b901a022461500111b4fbe",
      displayName: "Leung Kwok Yau",
      imageUrl: "",
      numberOfReviews: 6,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Leung, \n\nThank you for your review. \n\nI am pleased to read you were happy with the service and would recommend us. I will be sure to pass this on the surveyor! \n\nI am glad we were able to be of service to you. \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-21T07:46:30.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f607dd123c40b18d381637",
    filtered: false,
    pending: false,
    text: "Very efficient.\nVery quick to reply to any questions.",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: true,
        createdDateTime: "2025-10-20T11:58:53.000Z",
        reviewSourceName: "AFSv2",
        verificationSource: "invitation",
        verificationLevel: "verified",
        hasDachExclusion: false,
      },
    },
    title: "Very efficient.",
    likes: 0,
    source: "AFSv2",
    dates: {
      experiencedDate: "2025-10-12T00:00:00.000Z",
      publishedDate: "2025-10-20T11:58:53.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "68f607dda9dcb0c234fc9462",
      displayName: "N.Nunkoo",
      imageUrl: "",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: false,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Customer, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-20T12:57:21.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
  {
    id: "68f34c577061ba6f4ae44f29",
    filtered: false,
    pending: false,
    text: "Easy to use and quick to arrange the survey and send back the report. I would use them again. ",
    rating: 5,
    labels: {
      merged: null,
      verification: {
        isVerified: false,
        createdDateTime: "2025-10-18T10:14:15.000Z",
        reviewSourceName: "BasicLink",
        verificationSource: "invitation",
        verificationLevel: "invited",
        hasDachExclusion: false,
      },
    },
    title: "Easy to use and quick ",
    likes: 0,
    source: "BasicLink",
    dates: {
      experiencedDate: "2025-10-08T00:00:00.000Z",
      publishedDate: "2025-10-18T10:14:15.000Z",
      updatedDate: null,
      submittedDate: null,
    },
    report: null,
    hasUnhandledReports: false,
    consumer: {
      id: "68f34c4fb411c1256ac8c9f3",
      displayName: "Louise Relf",
      imageUrl:
        "https://user-images.trustpilot.com/68f34c4fb411c1256ac8c9f3/73x73.png",
      numberOfReviews: 1,
      countryCode: "GB",
      hasImage: true,
      isVerified: false,
    },
    reply: {
      message:
        "Dear Louise, \n\nThank you for your review. \n\nI am so pleased that you were happy with the service. We are delighted to have been of service to you. \n\nGood luck with everything! \n\nKind regards, \n\nAimee\nCustomer Services \n0203 936 9033",
      publishedDate: "2025-10-20T08:22:17.000Z",
      updatedDate: null,
    },
    consumersReviewCountOnSameDomain: 1,
    consumersReviewCountOnSameLocation: null,
    productReviews: [],
    language: "en",
    location: null,
  },
];

export const DEFAULT_CONTENT = {
  title: "<p>We’re rated <em>Excellent</em> on Trustpilot!</p>",
  description:
    "<p>Join the club of thousands of happy customers</p><p>who trust Houzecheck with their surveys.</p>",
  descriptionMobile:
    "<p>Join the club of thousands of happy customers who trust Houzecheck with their surveys.</p>",
  lastSlide: {
    description:
      "Thousands shared their reviews. Now it's your turn to experience the Houzecheck quality service.",
    primaryBtn: {
      label: "Book a Survey",
      url: "/book",
    },
    secondaryBtn: {
      label: "View More Reviews",
      url: "https://www.trustpilot.com/review/houzecheck.com",
    },
    title: "What Will Your Story Be?",
  },
};
